import time

from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.wait import WebDriverWait


class Customer:
    _name = ""
    text = "Hi this is automated message generated by Vedika"

    def __init__(self, driver):
        self.driver = driver

    @property
    def name(self):
        """getter for property name
        this property will be used to get the name of all the customers

        Returns:
            str: the name of customer
        """
        return self._name

    @name.setter
    def name(self, name):
        """setter for property name
        this is the setter method to set the name to each object of class customer

        Args:
            name(str): name of the customer
        """
        self._name = name

    def send_msg(self):
        """method for sending message
        this method will be used to send messages to the customers
        """
        inp_xpath_search = '//div[@class="_3FRCZ copyable-text selectable-text"][@contenteditable="true"][' \
                           '@data-tab="3"] '
        input_search_box = self.driver.find_element_by_xpath(inp_xpath_search)
        time.sleep(2)
        input_search_box.clear()
        input_search_box.send_keys(self.name + Keys.ENTER)
        time.sleep(2)
        inp_xpath = '//div[@class="_3FRCZ copyable-text selectable-text"][@contenteditable="true"][@data-tab="1"]'
        input_box = self.driver.find_element_by_xpath(inp_xpath)
        time.sleep(2)
        input_box.send_keys(self.text + Keys.ENTER)
        time.sleep(2)

    def receive_msg(self):
        """method for receiving message
        this method will be used to receive messages from the customers

        Returns:
            bool: True if there is new message otherwise False
        """
        inp_xpath_search = '//div[@class="_3FRCZ copyable-text selectable-text"][@contenteditable="true"][' \
                           '@data-tab="3"] '
        input_search_box = self.driver.find_element_by_xpath(inp_xpath_search)
        time.sleep(2)
        input_search_box.clear()
        input_search_box.send_keys(self.name)
        time.sleep(2)
        try:
            self.driver.find_element_by_xpath("//span[contains(@aria-label,'unread message')]")
            return True
        except NoSuchElementException:
            return False


